# Generated by Django 4.2.7 on 2024-03-06 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=150, verbose_name='Место')),
                ('time', models.TimeField(verbose_name='Время')),
                ('action', models.CharField(max_length=150, verbose_name='Действие')),
                ('is_pleasant_habit', models.BooleanField(default=False, verbose_name='Приятная привычка?')),
                ('periodicity', models.CharField(choices=[('once_a_day', 'Раз в день'), ('once_a_week', 'Раз в неделю'), ('once_a_month', 'Раз в месяц')], default='once_a_day', max_length=50, verbose_name='Периодичность')),
                ('remuneration', models.CharField(max_length=150, verbose_name='Вознаграждение')),
                ('time_to_complete', models.PositiveIntegerField(verbose_name='Время на выполнение')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовано?')),
                ('related_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.habit', verbose_name='Связанная привычка')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
            },
        ),
    ]
