# Generated by Django 4.2.7 on 2024-03-15 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('habit_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID привычки')),
                ('place', models.CharField(max_length=150, verbose_name='Место')),
                ('time', models.DateTimeField(verbose_name='Время, когда необходимо выполнить')),
                ('action', models.CharField(max_length=150, verbose_name='Действие')),
                ('is_pleasant_habit', models.BooleanField(default=False, verbose_name='Приятная привычка?')),
                ('periodicity', models.PositiveIntegerField(default=1, verbose_name='Периодичность')),
                ('remuneration', models.CharField(blank=True, max_length=150, null=True, verbose_name='Вознаграждение')),
                ('time_to_complete', models.PositiveIntegerField(verbose_name='Время на выполнение')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовано?')),
                ('related_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.habit', verbose_name='Связанная привычка')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
            },
        ),
    ]
